name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install Poetry
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Dump environment details
      run: |
        echo "OS/Runner: ${{ runner.os }}"
        echo "Python version:"
        python --version
        echo "Poetry version:"
        poetry --version
        echo "Poetry Environment Info:"
        poetry env info
        echo "PATH:"
        echo $PATH
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction -vv --with dev

    - name: Verify Dependency Tree
      run: poetry show --tree

    - name: Run Unit Tests
      run: poetry run pytest -vv tests/ -m "not integration" --cov=./ --cov-report=xml:coverage-unit.xml

    - name: Run Integration Tests
      run: poetry run pytest -vv tests/ -m "integration" --cov=./ --cov-report=xml:coverage-integration.xml

    - name: Upload Unit Test coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@4fa83a1e53a3bcf52199b03653b47f401f855e2d # v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage-unit.xml
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}-unit
        fail_ci_if_error: true
        verbose: true

    - name: Upload Integration Test coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@4fa83a1e53a3bcf52199b03653b47f401f855e2d # v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage-integration.xml
        flags: ${{ matrix.os }}-py${{ matrix.python-version }}-integration
        fail_ci_if_error: true
        verbose: true

    - name: Upload reports and logs on failure
      uses: actions/upload-artifact@3446296876d12d3c53597d3969b75833d74ab896 # v4.3.4
      if: failure()
      with:
        name: ci-failure-reports-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          coverage-unit.xml
          coverage-integration.xml